spring:

  application:
    name: swagger

  # Producer properties kafka
#  kafka:
#    producer:
#      bootstrap-servers: kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      group-id: group-customer
#  # Consumer properties kafka
#    consumer:
#      bootstrap-servers: kafka:9092
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: group-customer
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true
topic:
  name:
    producer: tp-send-customer
    consumer: tp-send-customer #tp-receive-customer

clients:
  address:
    url: https://viacep.com.br/ws

# Configuração Prometheus
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
